version: 0.2

env:
  secrets-manager:
    FirebaseToken: "FIREBASE_ACCESS:FIREBASE_ACCESS_TOKEN"
    AppID: "FIREBASE_ACCESS:APP_ID"
    Tester_Group: "FIREBASE_ACCESS:TESTER_GROUP"

phases:
  build:
    commands:
      - apt install -y wget
      - wget https://github.com/firebase/firebase-tools/releases/download/v11.0.1/firebase-tools-linux
      - chmod +x ./firebase-tools-linux
      - echo Entering Build Phase
      - chmod +x gradlew
      - ./gradlew build
      - echo "Uploading to Firebase"
      - ./firebase-tools-linux appdistribution:distribute ./app/build/outputs/apk/debug/app-debug.apk --app ${AppID} --groups ${AppID} --token "${Tester_Group}" --release-notes-file ReleaseNotes.txt