version: 0.2

env:
  parameter-store:
    SERVICE_CREDENTIALS: "/ssfe/android/test/SERVICE_CREDENTIALS"
   
phases:
  build:
    commands:
      - echo Entering Build Phase
      - echo $SERVICE_CREDENTIALS > key.json
      - cat key.json
