version: 0.2

env:
  variables:
    PRODUCTION_SERVER_ENV: "prod"
    JKSPATH: "./app/ShearShare.jks"
  parameter-store:
    KEY_STORE_TOKEN: "/ssfe/android/$SERVER_ENV/KEY_STORE_TOKEN"
    APP_ID: "/ssfe/android/$SERVER_ENV/APP_ID"
    TEST_GROUP_ID: "/ssfe/android/$SERVER_ENV/TEST_GROUP_ID"

phases:
  build:
    commands:
      - echo Entering Build Phase
      - echo "Starting $SERVER_ENV build"
      - | 
         if [ $SERVER_ENV == $PRODUCTION_SERVER_ENV ]
         then
            echo "Build Started"
            chmod +x gradlew
            ./gradlew build
            echo "Signing the apk"
            apksigner sign --ks ./app/ShearShare.jks --ks-pass pass:${KEY_STORE_TOKEN} ./app/build/outputs/apk/release/app-release-unsigned.apk
            echo "Uploading to Play Store"
            echo "Verifying the signed apk"
            apksigner verify --print-certs ./app/build/outputs/apk/release/app-release-unsigned.apk
         else
            #apt install -y wget
            #wget -q https://github.com/firebase/firebase-tools/releases/download/v11.0.1/firebase-tools-linux
            #chmod +x ./firebase-tools-linux
            echo "Starting Test build"
            chmod +x gradlew
            #./gradlew build
            ./gradlew bundleRelease
            #echo "Uploading to Firebase"
            #./firebase-tools-linux appdistribution:distribute ./app/build/outputs/apk/debug/app-debug.apk --app ${APP_ID} --groups ${TEST_GROUP_ID} --token "${KEY_STORE_TOKEN}" --release-notes-file ReleaseNotes.txt
         fi
artifacts:
  files:
    - './app/*'
  name: builds/$CODEBUILD_BUILD_NUMBER/my-artifacts 
    
      #- java -jar release-manager-1.3.jar -key semiotic-effort-265920-e52c804c6a24.json -file ./app/build/outputs/apk/release/app-release-unsigned.apk -track internal -name "My First Project" -notes "First release"
