version: 0.2

phases:
  build:
    commands:
      - echo Entering Build Phase
      - docker --version
      - chmod +x gradlew
      - ./gradlew build

artifacts:
  files:
    - app/build/outputs/apk/app-debug.apk