version: 0.2

phases:
  build:
    commands:
      - echo Entering Build Phase
      #- docker --version
      - ls -a
      - #docker pull androidsdk/android-29
      - #docker run -it androidsdk/android-29 /bin/sh
      - chmod +x gradlew
      - ./gradlew build

artifacts:
  files:
    - app/build/outputs/apk/app-debug.apk
