version: 0.2

env:
  parameter-store:
    FirebaseToken: "/ssfe/FIREBASE_ACCESS_TOKEN"
    AppID: "/ssfe/android/APPID"
    Tester_Group: "/ssfe/android/TESTER_GROUP"
    KeystorePassword: "/ssfe/android/KeystorePassword"

phases:
  build:
    commands:
      - apt install -y wget
      - wget https://github.com/firebase/firebase-tools/releases/download/v11.0.1/firebase-tools-linux
      - chmod +x ./firebase-tools-linux
      - echo Entering Build Phase
      - chmod +x gradlew
      - ./gradlew build
      - echo "Uploading to Firebase"
      - ./firebase-tools-linux appdistribution:distribute ./app/build/outputs/apk/release/app-release.apk --app ${AppID} --groups ${Tester_Group} --token "${FirebaseToken}" --release-notes-file ReleaseNotes.txt
      - echo "Signing the apk"
      - apksigner sign --ks rootca.jks --ks-pass pass:${KeystorePassword} app-release-unsigned.apk
      - echo "Verifying the signed apk"
      - apksigner verify --print-certs app-release-unsigned.apk
