version: 0.2

#env:
 # parameter-store:
  #  KeystorePassword: "/ssfe/android/production/KeystorePassword"

phases:
  build:
    commands:
      - echo Entering Build Phase
      - | 
         if [ $SERVER_ENV == "prod" ]
         then
            echo "Starting Prod build"
         else
            echo "Starting Test build"
         fi
      #- chmod +x gradlew
      #- ./gradlew build
      #- echo "Uploading to Firebase"
      #- echo "Signing the apk"
      #- apksigner sign --ks ./app/ShearShare.jks --ks-pass pass:${KeystorePassword} ./app/build/outputs/apk/release/app-release-unsigned.apk
      #- echo "Verifying the signed apk"
      #- apksigner verify --print-certs ./app/build/outputs/apk/release/app-release-unsigned.apk
      #- java -jar release-manager-1.3.jar -key semiotic-effort-265920-e52c804c6a24.json -file ./app/build/outputs/apk/release/app-release-unsigned.apk -track internal -name "My First Project" -notes "First release"
